[RFC] Fix - Project Set UP
Prakash-Kuikel/blog pull request #1
Opened 2022-08-22 07:08 UTC by Prakash-Kuikel

`git fetch && git checkout feature/project-set-up`

#### Description
1.

2022-08-22 11:02 UTC, dorjikhandu21 approved these changes
LGTM

2022-08-22 13:12 UTC, rnzdoj requested changes

2022-08-22 13:12 UTC, rnzdoj commented on app/graphql/types/mutation_type.rb
> +    field :test_field, String, null: false,
remove this test field

2022-08-22 13:12 UTC, rnzdoj commented on app/graphql/types/query_type.rb
> +    field :test_field, String, null: false,
this field as well

2022-08-22 13:12 UTC, rnzdoj commented on Gemfile
> +end
user pry instead of debug, and pry-rails.

2022-08-22 13:12 UTC, rnzdoj commented on Gemfile
> +end
new line here

2022-08-22 13:12 UTC, rnzdoj commented on Gemfile
> +# frozen_string_literal: true
didn't lint this file?

2022-08-23 04:13 UTC, Prakash-Kuikel commented on app/graphql/types/mutation_type.rb
> +    field :test_field, String, null: false,
Done

2022-08-23 04:13 UTC, Prakash-Kuikel commented on app/graphql/types/query_type.rb
> +    field :test_field, String, null: false,
Done

2022-08-23 04:13 UTC, Prakash-Kuikel commented on Gemfile
> +end
Done

2022-08-23 04:14 UTC, Prakash-Kuikel commented on Gemfile
> +end
Done

2022-08-23 04:26 UTC, Prakash-Kuikel commented on Gemfile
> +# frozen_string_literal: true
Done

2022-08-23 05:52 UTC, rnzdoj approved these changes

2022-08-23 09:56 UTC, merged